[Actions] Fixes workflow "release"
MaFeLP/discord_bots pull request #7
Opened 2021-12-22 23:21 UTC by MaFeLP

This fixes the tagging of docker images, as it removes the leading `ref/tags/` from the tag name.

## What has happened?
The variable `${{ github.ref }}` gave a tag name in the reference format back: e. g. [`refs/tags/v0.1.0`](https://github.com/MaFeLP/discord_bots/actions/runs/1613337558). As docker is not able to tag an image named `ghcr.io/MaFeLP/discord_bots:refs/tags/v0.1.0` due to an invalid tagging format (too many slashes).

## How was it fixed?
This Commit updates the [release.yml](./.github/workflows/release.yml) file to include a step in which `refs/tags/` is cut from the tag name. Therefore no issues should occur, when pushing tags.

2021-12-22 23:26 UTC, lxgr-linux requested changes

2021-12-22 23:26 UTC, lxgr-linux commented on .github/workflows/release.yml
> +      - name: Extract Tag name
```suggestion
      - name: Extract tag name
```

2021-12-23 08:48 UTC, lxgr-linux approved these changes

2021-12-23 10:58 UTC, G0rger approved these changes
LGTM

2021-12-23 19:22 UTC, G0rger approved these changes

2021-12-23 19:24 UTC, G0rger commented
As I can't request a change for parts without changes:
https://github.com/MaFeLP/discord_bots/blob/18fea14455ba560327ccefa014dac98cbf795ae9/.github/workflows/release.yml#L20
```
      - name: Make Repository name lowercase
```
shouldn't it be:
```
      - name: Make repository name lowercase
```

2021-12-23 23:17 UTC, MaFeLP commented
Merged in 6a9ba290b1b0edca08c64bdaa896f1e09826005d

2021-12-23 23:17 UTC, closed without merging